fix_seed: 0
checkpoints_every: 1
tensorboard_log: True
tqdm_progress_bar: True
result_path: ./results/test/

model:
  model_name: facebook/esm2_t12_35M_UR50D
  hidden_size: 480
  freeze_backbone: True
  freeze_embeddings: True
  freeze_backbone_layers: 10
  classifier_dropout_rate: 0.5
  backbone_dropout_rate: 0.30

train_settings:
#  train_path: ./ptm_data/train/final_Phosphorylation.csv
#  train_path: ./ptm_data/train/final_phosphorylation_Y.csv
#  train_path: ./ptm_data/train/final_phosphorylation_S_and_T.csv
#  train_path: ./ptm_data/train/final_Acetylation.csv
#  train_path: ./ptm_data/train/final_Methylation.csv
#  train_path: ./ptm_data/train/final_N-linked_Glycosylation.csv
  train_path: ./ptm_data/train/final_O-linked_Glycosylation.csv
#  train_path: ./ptm_data/train/final_Succinylation.csv
#  train_path: ./ptm_data/train/final_Ubiquitylation.csv

  num_epochs: 24
  shuffle: True
  mixed_precision: bf16
  batch_size: 8
  num_workers: 4
  grad_accumulation: 4
  grad_clip_norm: 1
  alpha: 0.5
  gamma: 1
  label_smoothing: 0.1
  max_sequence_length: 768

test_settings:
#  test_path: ./ptm_data/test/final_Phosphorylation.csv
#  test_path: ./ptm_data/test/final_phosphorylation_Y.csv
#  test_path: ./ptm_data/test/final_phosphorylation_S_and_T.csv
#  test_path: ./ptm_data/test/final_Acetylation.csv
#  test_path: ./ptm_data/test/final_Methylation.csv
#  test_path: ./ptm_data/test/final_N-linked_Glycosylation.csv
  test_path: ./ptm_data/test/final_O-linked_Glycosylation.csv
#  test_path: ./ptm_data/test/final_Succinylation.csv
#  test_path: ./ptm_data/test/final_Ubiquitylation.csv

  batch_size: 8

valid_settings:
#  valid_path: ./ptm_data/valid/final_Phosphorylation.csv
#  valid_path: ./ptm_data/valid/final_phosphorylation_Y.csv
#  valid_path: ./ptm_data/valid/final_phosphorylation_S_and_T.csv
#  valid_path: ./ptm_data/valid/final_Acetylation.csv
#  valid_path: ./ptm_data/valid/final_Methylation.csv
#  valid_path: ./ptm_data/valid/final_N-linked_Glycosylation.csv
  valid_path: ./ptm_data/valid/final_O-linked_Glycosylation.csv
#  valid_path: ./ptm_data/valid/final_Succinylation.csv
#  valid_path: ./ptm_data/valid/final_Ubiquitylation.csv

  batch_size: 8
  num_workers: 0

optimizer:
  name: adam
#  name: sgd
  lr: 5e-5
  weight_decouple: True
  weight_decay: 1e-2
  eps: 1e-16
  beta_1: 0.9
  beta_2: 0.999
  use_8bit_adam: False
  grad_clip_norm: 1
  decay:
    warmup: 512
    min_lr: 0
    gamma: 0.2
    num_restarts: 1
  nesterov: true
  momentum: 0.90

scheduler:
#    name: multistep_lr
    name: cosine_annealing
#    name: cosine_annealing_warm_restarts
#    name: cosine_annealing_sequential

    T_max: 24
    T_0: 24
    T_mult: 2
    eta_min: 0
    eta_min_first: 0.0005
    eta_min_second: 0.00001
